language: nodejs
node_js:
  - node

before_script:
  - npm run setup
  - npm run build

script:
  - npm run test

after_success:
  - npm run typedoc
  - npm pack

#before_deploy:

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: 00543b2469d1145dd1da8b003dc4488bfcea92a7
    on:
      tags: true
  - provider: releases
    api_key: 00543b2469d1145dd1da8b003dc4488bfcea92a7
    file_glob: true
    file: "{YOURLIB}-*.tgz"
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    skip_cleanup: true
    email: "crimelero@hotmail.com"
    api_key: f142c412-827c-4270-b6cf-2356421e6e15
    on:
      tags: true