openapi: 3.0.3
info:
  title: IOT API
  version: 1.0.0
servers:
  #- url: http://localhost/
  - url: "{protocol}://{environment}:{port}/"
    variables:
      protocol:
        default: http
        enum:
          - http
          - https
      environment:
        default: localhost # Production server
        enum:
          - localhost # Production server
          - api.dev # Development server
          - api.staging # Staging server
      port:
        default: "3000"
      # version:
      #   default: ""
      #   enum:
      #     - ""
      #     - "v1/"
      # basePath:
      #   default: ""
      #   enum:
      #     - ""
      #     - "mobile_app/"
      #     - "ux/"
# - url: https://staging.gigantic-server.com/v1
#   description: Staging server
#   variables:
#     port:
#       default: '3000'
#     basePath:
#       default: v1
# - url: https://api.gigantic-server.com/v1
#   description: Production server
#   variables:
#     port:
#       default: '3000'
#     basePath:
#       default: v1
paths:
  ####################################
  #           ROUTES
  ####################################
  ######## GREET START ############
  /greet:
    x-exegesis-controller: mongoCrud
    get:
      x-exegesis-operationId: readMany
      tags:
        - Greet
      responses:
        200:
          $ref: "#/components/responses/200"
          content:
            application/json:
            schema:
              $ref: "#/components/schemas/Greet"
        404:
          $ref: "#/components/responses/404"
    post:
      x-exegesis-operationId: create
      tags:
        - Greet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Greet"
      responses:
        200:
          $ref: "#/components/responses/200"
        404:
          $ref: "#/components/responses/404"
  /greet/{_id}:
    x-exegesis-controller: mongoCrud
    put:
      x-exegesis-operationId: update
      tags:
        - Greet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Greet"
      parameters:
        - in: path
          name: _id
          schema:
            type: string
          required: true
      responses:
        200:
          $ref: "#/components/responses/200"
        404:
          $ref: "#/components/responses/404"
    get:
      x-exegesis-operationId: readOne
      tags:
        - Greet
      parameters:
        - in: path
          name: _id
          schema:
            type: string
          required: true
      responses:
        200:
          $ref: "#/components/responses/200"
        404:
          $ref: "#/components/responses/404"
    delete:
      summary: "Delete example"
      x-exegesis-operationId: remove
      tags:
        - Greet
      parameters:
        - in: path
          name: _id
          schema:
            type: string
          required: true
      responses:
        200:
          $ref: "#/components/responses/200"
        404:
          $ref: "#/components/responses/404"

  ######## GREET END ############

  ######## USER START ############
  /user:
    x-exegesis-controller: mongoCrud
    get:
      x-exegesis-operationId: readMany
      tags:
        - User
      responses:
        200:
          $ref: "#/components/responses/200"
          content:
            application/json:
            schema:
              $ref: "#/components/schemas/User"
        404:
          $ref: "#/components/responses/404"
    post:
      summary: "Create new user"
      x-exegesis-operationId: create
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        200:
          $ref: "#/components/responses/200"
        404:
          $ref: "#/components/responses/404"
  /user/{_id}:
    x-exegesis-controller: mongoCrud
    put:
      summary: "Update example"
      x-exegesis-operationId: update
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      parameters:
        - in: path
          name: _id
          schema:
            type: string
          required: true
      responses:
        200:
          $ref: "#/components/responses/200"
        404:
          $ref: "#/components/responses/404"
    get:
      summary: "Find example"
      description: Returns example by Id
      x-exegesis-operationId: readOne
      tags:
        - User
      parameters:
        - in: path
          name: _id
          schema:
            type: string
          required: true
      responses:
        200:
          $ref: "#/components/responses/200"
        404:
          $ref: "#/components/responses/404"
    delete:
      summary: "Delete example"
      x-exegesis-operationId: remove
      tags:
        - User
      parameters:
        - in: path
          name: _id
          schema:
            type: string
          required: true
      responses:
        200:
          $ref: "#/components/responses/200"
        404:
          $ref: "#/components/responses/404"

  ######## USER END ############
  ########### AUTH START ###############
  /login:
    x-exegesis-controller: authController
    post:
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
            example:
              email: user@example.com
              password: U3dhZ2dlciByb2Nrcw==

      security: []
      x-exegesis-operationId: login
      summary: Return JWT token
      description: >-
        This is an example opeartion to show how security is applied to the
        call.
      responses:
        "200":
          description: OK
  /logout:
    x-exegesis-controller: authController
    get:
      x-exegesis-operationId: logout
      tags:
        - auth
      responses:
        "200":
          description: OK

########### AUTH END ###############

####################################
#           MODELS
# https://swagger.io/docs/specification/data-models/keywords/
####################################
components:
  schemas:
    User:
      description: Users for API auth
      type: object
      x-openapi-mongoose:
        exclude-schema: false
        schema-options:
          timestamps: false
      required:
        - email
        - password
      properties:
        fullName:
          type: string
          maxLength: 120
          uniqueItems: true
        email:
          type: string
          format: email
          maxLength: 200
          uniqueItems: true
        password:
          description: base64-encoded characters, for example,
          example: U3dhZ2dlciByb2Nrcw==
          type: string
          writeOnly: true
          format: byte
        passwordResetToken:
          type: integer
          description: A JS timestamp (epoch ms) representing the moment when this user\'s `passwordResetToken` will expire (or 0 if the user currently has no such token).
          example: 1502844074211
        lastSeenAt:
          type: integer
          description: A JS timestamp (epoch ms) representing the moment at which this user most recently interacted with the backend while logged in (or 0 if they have not interacted with the backend at all yet).
          example: 1502844074211
        emailStatus:
          description: The confirmation status of the user\'s email address.
          type: string
          enum: ["unconfirmed", "change-requested", "confirmed"]
    Greet:
      description: A greeting for the user.
      type: object
      required:
        - name
      # x-openapi-mongoose:
      #   additional-properties:
      #     Users:
      #       $ref: "#/components/schemas/User"
      #       approved:
      #         type: string
      #         format: datetime
      #       rejected:
      #         type: string
      #         format: datetime
      #   type: string
      properties:
        name:
          type: string
        Users:
          type: string

    ErrorModel:
      type: object
      required:
        - message
        - code
      properties:
        message:
          type: string
        code:
          type: integer
          minimum: 100
          maximum: 600

  ##################################
  #      RESPONSES
  # Based on: https://opensource.zalando.com/restful-api-guidelines/#http-requests
  ###############################3
  responses:
    200:
      description: "Ok"
    400:
      description: "Bad request"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorModel"
    404:
      description: "Not Found"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorModel"
  #########################
  #   SECURITY
  ###########################
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      description: Token value, if you not have use the default to test ''
      type: http
      scheme: bearer
      bearerFormat: JWT # optional, arbitrary value for documentation purposes
security:
  - bearerAuth: [] # use the same name as above

# x-openapi-mongoose:
#   additional-properties:
#     user:
#      $ref: "#/definitions/User"
#     approved:
#      type: string
#       format: datetime
#     rejected:
#       type: string
#       format: datetime
#    exclude-schema: true // by default false
#   schema-options:
#     timestamps: true
