openapi: 3.0.1
info:
  title: My API
  version: 1.0.0

# servers:
# - url: http://localhost:3000/v1/
#   description: Development server
  # variables:
  #   port:
  #     default: '3000'
  #   basePath:
  #     default: v1
# - url: https://staging.gigantic-server.com/v1
#   description: Staging server
#   variables:
#     port:
#       default: '3000'
#     basePath:
#       default: v1
# - url: https://api.gigantic-server.com/v1
#   description: Production server
#   variables:
#     port:
#       default: '3000'
#     basePath:
#       default: v1
paths:
  /greet:
    x-exegesis-controller: greet/greetController
    get:
      summary: Greets the user
      x-exegesis-operationId: getGreeting
      parameters:
        - description: The name of the user to greet.
          name: name
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: A greeting for the user.
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string